---
title: "Differential expression analysis of proteins"
format:
  html:
    df-print: paged
    embed-resources: true
---

```{r}
#| message: false
library(ggpubr)
library(ggrepel)
library(OlinkAnalyze)
library(tidyverse)
```

## Read data

```{r}
#| message: false
pdata <- read_tsv("../data/PRETTY_NPX_138samp_326prot_QCed.tsv") |> 
    mutate(
      group = factor(group, levels = c(1, 0)),
      nadm = factor(nadm, levels = c(1, 0)),
      mace = factor(mace, levels = c(1, 0)),
      death_all = factor(death_all, levels = c(1, 0))
    )
```

## Group

```{r}
dep_group <- olink_ttest(pdata, "group") |>
  mutate(prot_exp = case_when(estimate >= 0 & Adjusted_pval <= 0.05 ~ "Up",
                              estimate <= 0 & Adjusted_pval <= 0.05 ~ "Down",
                              TRUE ~ "n.s."))
dep_group
# dep_group |> write_csv("../data/dep_group.csv")
```

```{r}
# Colours, size, and alpha parameters
cols <- c("Up" = "#ffad73", "Down" = "#26b3ff", "n.s." = "grey") 
sizes <- c("Up" = 2, "Down" = 2, "n.s." = 1) 
alphas <- c("Up" = 1, "Down" = 1, "n.s." = 0.5)
# Volcano plot
p1 <- dep_group %>%
  ggplot(aes(x = estimate,
             y = -log10(p.value),
             fill = prot_exp,
             alpha = prot_exp,
             label = Assay)) +
  geom_point(shape = 21, colour = "black") +
  geom_hline(yintercept = -log10(0.0051),
             linetype = "dashed") +
  # geom_text_repel(data = dep_group[dep_group$Threshold == "Significant",
  #                                   c("Assay", "estimate", "p.value", "prot_exp")],
  #                  box.padding = 0.1, max.overlaps = 20, size = 3) +
  scale_fill_manual(values = cols) + # Modify point colour
  scale_alpha_manual(values = alphas,) +
  xlim(-1.1, 1.1) +
  theme_bw() +
  # theme(legend.position = c(0.9, 0.1),
  #       legend.background = element_rect(fill = "white", color = "black"),
  #       text = element_text(size = 13)) +
  theme(legend.position = "none") +
  labs(fill = "   Protein\nexpression",
       title = "PWH with vs without SNAEs",
       x = expression(log[2](FC)),
       y = expression(-log[10](p-value))) +
  guides(alpha = "none")
p1
```

## NADM

```{r}
dep_nadm <- olink_ttest(pdata, "nadm") |>
  mutate(prot_exp = case_when(estimate >= 0 & Adjusted_pval <= 0.05 ~ "Up",
                              estimate <= 0 & Adjusted_pval <= 0.05 ~ "Down",
                              TRUE ~ "n.s."))
# dep_nadm |> write_csv("../data/dep_nadm.csv")
```

```{r}
# Colours, size, and alpha parameters
cols <- c("Up" = "#ffad73", "Down" = "#26b3ff", "n.s." = "grey") 
sizes <- c("Up" = 2, "Down" = 2, "n.s." = 1) 
alphas <- c("Up" = 1, "Down" = 1, "n.s." = 0.5)
# Volcano plot
p2 <- dep_nadm %>%
  ggplot(aes(x = estimate,
             y = -log10(p.value),
             fill = prot_exp,
             alpha = prot_exp,
             label = Assay)) +
  geom_point(shape = 21, colour = "black") +
  geom_hline(yintercept = -log10(0.0080),
             linetype = "dashed") +
  # geom_label_repel(data = dep_nadm[dep_nadm$Threshold == "Significant",
  #                                   c("Assay", "estimate", "p.value", "prot_exp")],
  #                  box.padding = 0.5, max.overlaps = 20) +
  scale_fill_manual(values = cols) + # Modify point colour
  scale_alpha_manual(values = alphas,) +
  xlim(-1.1, 1.1) +
  theme_bw() +
  # theme(legend.position = c(0.9, 0.1),
  #       legend.background = element_rect(fill = "white", color = "black"),
  #       text = element_text(size = 13)) +
  theme(legend.position = "none") +
  labs(fill = "   Protein\nexpression",
       title = "PWH with vs without neoplasias",
       x = expression(log[2](FC)),
       y = expression(-log[10](p-value))) +
  guides(alpha = "none")
p2
```

## MACE

```{r}
dep_mace <- olink_ttest(pdata, "mace") |>
  mutate(prot_exp = case_when(estimate >= 0 & Adjusted_pval <= 0.05 ~ "Up",
                              estimate <= 0 & Adjusted_pval <= 0.05 ~ "Down",
                              TRUE ~ "n.s."))
# dep_mace |> write_csv("../data/dep_mace.csv")
```

```{r}
# Colours, size, and alpha parameters
cols <- c("Up" = "#ffad73", "Down" = "#26b3ff", "n.s." = "grey") 
sizes <- c("Up" = 2, "Down" = 2, "n.s." = 1) 
alphas <- c("Up" = 1, "Down" = 1, "n.s." = 0.5)
# Volcano plot
p3 <- dep_mace %>%
  ggplot(aes(x = estimate,
             y = -log10(p.value),
             fill = prot_exp,
             alpha = prot_exp,
             label = Assay)) +
  geom_point(shape = 21, colour = "black") +
  # geom_hline(yintercept = -log10(0.0051),
  #            linetype = "dashed") +
  # geom_label_repel(data = dep_mace[dep_mace$Threshold == "Significant",
  #                                   c("Assay", "estimate", "p.value", "prot_exp")],
  #                  box.padding = 0.5, max.overlaps = 20) +
  scale_fill_manual(values = cols) + # Modify point colour
  scale_alpha_manual(values = alphas,) +
  xlim(-1.1, 1.1) +
  theme_bw() +
  # theme(legend.position = c(0.9, 0.1),
  #       legend.background = element_rect(fill = "white", color = "black"),
  #       text = element_text(size = 13)) +
  theme(legend.position = "none") +
  labs(fill = "   Protein\nexpression",
       title = "PWH with vs without CV events",
       x = expression(log[2](FC)),
       y = expression(-log[10](p-value))) +
  guides(alpha = "none")
p3
```

## Death_all

```{r}
dep_death_all <- olink_ttest(pdata, "death_all") |>
  mutate(prot_exp = case_when(estimate >= 0 & Adjusted_pval <= 0.05 ~ "Up",
                              estimate <= 0 & Adjusted_pval <= 0.05 ~ "Down",
                              TRUE ~ "n.s."))
# dep_death_all |> write_csv("../data/dep_death_all.csv")
```

```{r}
# Colours, size, and alpha parameters
cols <- c("Up" = "#ffad73", "Down" = "#26b3ff", "n.s." = "grey") 
sizes <- c("Up" = 2, "Down" = 2, "n.s." = 1) 
alphas <- c("Up" = 1, "Down" = 1, "n.s." = 0.5)
# Volcano plot
p4 <- dep_death_all %>%
  ggplot(aes(x = estimate,
             y = -log10(p.value),
             fill = prot_exp,
             alpha = prot_exp,
             label = Assay)) +
  geom_point(shape = 21, colour = "black") +
  geom_hline(yintercept = -log10(0.0018),
             linetype = "dashed") +
  # geom_label_repel(data = dep_death_all[dep_death_all$Threshold == "Significant",
  #                                   c("Assay", "estimate", "p.value", "prot_exp")],
  #                  box.padding = 0.5, max.overlaps = 20) +
  scale_fill_manual(values = cols) + # Modify point colour
  scale_alpha_manual(values = alphas,) +
  xlim(-1.1, 1.1) +
  theme_bw() +
  # theme(legend.position = c(0.9, 0.1),
  #       legend.background = element_rect(fill = "white", color = "black"),
  #       text = element_text(size = 13)) +
  theme(legend.position = "none") +
  labs(fill = "   Protein\nexpression",
       title = "PWH with vs without mortality",
       x = expression(log[2](FC)),
       y = expression(-log[10](p-value))) +
  guides(alpha = "none")
p4
```

```{r}
# svg("../data/fig1AtoD.svg", width = 7, height = 5)
ggarrange(p1, p2, p3, p4, labels = c("A", "B", "C", "D"))
# dev.off()
```
