---
title: "RNA-seq analysis"
format:
  html:
    df-print: paged
    embed-resources: true
---

```{r}
#| message: false
library(AnnotationDbi)
library(biomaRt)
library(org.Hs.eg.db)
library(DESeq2)
library(ggpubr)
library(ggrepel)
library(haven)
library(pheatmap)
library(RColorBrewer)
library(readxl)
library(tidyverse)
```

```{r}
load("../data/deseq2.dds.RData")
```

## dds inspection

```{r}
head(counts(dds)) # to check the raw counts
```

```{r}
colData(dds) # to check the sample info
```

```{r}
design(dds) # to check the design formula
```

## Reorganisation of dds object

```{r}
id_pbmc <- read_xlsx("../data/id_group_PBMC.xlsx") |> 
  mutate(rnaseqid = gsub("-", "_", IDTUBO)) |> 
  dplyr::select(id_sample, rnaseqid)
```

```{r}
mdata <- read_dta("../data/PRETTY_metadata.dta") |> 
    dplyr::select(id:group, age:sex, art_reg, nadm:death_all, id_muestra)
```

```{r}
mdata <- id_pbmc |> 
  left_join(mdata, by = c("id_sample" = "id_muestra")) |> 
  filter(rnaseqid %in% colnames(dds)) |> 
  dplyr::select(rnaseqid, group, nadm:death_all, art_reg, age, sex, centro, id, id_sample) |> 
  mutate(group = ifelse(group == 0, 1, 0),
         death_all = ifelse(is.na(death_all), 0, 1)) |> 
  mutate(across(c(group, nadm, mace, death_all), factor))
```

Reorder in the same order as in dds object:

```{r}
mdata <- mdata |> 
  dplyr::slice(match(colnames(dds), rnaseqid))
```

Assign names to rows of metadata:

```{r}
rownames(mdata) <- mdata$rnaseqid
```

Fill the dds colData with the generated metadata:

```{r}
colData(dds) <- DataFrame(mdata)
```

#### Check that sample names match in both files

```{r}
all(colnames(dds$counts) %in% rownames(mdata)) # Must be TRUE
```

```{r}
all(colnames(dds$counts) == rownames(mdata)) # Must be TRUE
```

## Pre-filtering

```{r}
smallestGroupSize <- 3

keep <- rowSums(counts(dds) >= 10) >= smallestGroupSize
dds_filtered <- dds[keep, ]
```

## Help functions

```{r}
# A function to run DESeq2
run_deseq <- function(dds, design_var) {
  dds_tmp <- DESeqDataSet(dds, design = as.formula(paste0("~ ", design_var)))
  dds_tmp <- DESeq(dds_tmp)
  res <- results(dds_tmp)
  list(dds = dds_tmp, res = res)
}
```

```{r}
# A function for Ensembl annotation
library(biomaRt)

annotate_genes <- function(ensembl_ids) {
  mart <- useEnsembl("genes", "hsapiens_gene_ensembl")

  getBM(
    attributes = c(
      "ensembl_gene_id",
      "external_gene_name",
      "description",
      "gene_biotype"
    ),
    filters = "ensembl_gene_id",
    values = unique(ensembl_ids),
    mart = mart
  )
}
```

```{r}
tidy_results <- function(res, lfc = 0, alpha = 0.05, filter_sig = TRUE) {

  # 1. Convert DESeq2 results to tibble and classify genes
  res_tb <- as_tibble(res) |>
    mutate(
      gene = rownames(res),
      diffexpressed = case_when(
        log2FoldChange >  lfc & padj < alpha ~ "upregulated",
        log2FoldChange < -lfc & padj < alpha ~ "downregulated",
        TRUE ~ "not_de"
      )
    ) |>
    relocate(gene)

  # 2. Annotate ALL genes
  annot <- annotate_genes(res_tb$gene) |>
    mutate(
      description = sub("\\s*\\[.*\\]$", "", description)
    )

  # 3. Join annotation
  res_tb <- res_tb |>
    left_join(
      annot,
      by = c("gene" = "ensembl_gene_id")
    ) |> 
    arrange(pvalue)

  # 4. Optionally filter significant genes
  if (filter_sig) {
    res_tb <- res_tb |> filter(padj < alpha)
  }

  return(res_tb)
}


```

```{r}
# A function for volcano plots
plot_volcano <- function(
  res_tb,
  title,
  lfc_cutoff = 1,
  p_cutoff = 0.05,
  fdr_cutoff = 0.05,
  label_pc_only = TRUE,
  max_overlaps = 20
) {
  
  cols <- c("upregulated" = "#ffad73", "downregulated" = "#26b3ff", "not_de" = "grey") 
  sizes <- c("upregulated" = 2, "downregulated" = 2, "not_de" = 1) 
  alphas <- c("upregulated" = 1, "downregulated" = 1, "not_de" = 0.5)
  
  # Compute FDR threshold on p-value scale
  fdr_p_line <- max(
    res_tb$pvalue[res_tb$padj < fdr_cutoff],
    na.rm = TRUE
  )

  # Prepare labels (do NOT modify original table)
  plot_tb <- res_tb |>
    mutate(
      genelabels = ifelse(
        diffexpressed != "not_de" &
          (!label_pc_only | gene_biotype == "protein_coding"),
        external_gene_name,
        ""
      )
    )

  ggplot(
    plot_tb,
    aes(
      x = log2FoldChange,
      y = -log10(pvalue),
      fill = diffexpressed,
      alpha = diffexpressed#,
      #label = genelabels
    )
  ) +
    geom_point(shape = 21, colour = "black") +
    geom_vline(
      xintercept = c(-lfc_cutoff, lfc_cutoff),
      linetype = "dashed",
      linewidth = 0.2,
      colour = "black"
    ) +
    geom_hline(yintercept = -log10(fdr_p_line), linetype = "dashed") +
    scale_fill_manual(values = cols) +
    scale_alpha_manual(values = alphas) +
    theme_bw() +
    theme(
      legend.position = "none"
    ) +
    labs(
      title = title,
      x = expression(log[2](FC)),
      y = expression(-log[10](p-value))
    ) +
    guides(alpha = "none") #+
    # ggrepel::geom_label_repel(
    #   box.padding = 0.5,
    #   max.overlaps = max_overlaps,
    #   size = 3
    #)
}
```

## Run analyses

```{r}
res_group      <- run_deseq(dds_filtered, "group")
res_nadm       <- run_deseq(dds_filtered, "nadm")
res_mace       <- run_deseq(dds_filtered, "mace")
res_death_all  <- run_deseq(dds_filtered, "death_all")
```

## Tidy + plot

```{r}
tb_group <- tidy_results(res_group$res, filter_sig = FALSE)
tb_nadm  <- tidy_results(res_nadm$res, filter_sig = FALSE)
tb_mace  <- tidy_results(res_mace$res, filter_sig = FALSE)
tb_death <- tidy_results(res_death_all$res, filter_sig = FALSE)
```

## Export results

```{r}
# write.csv(tb_group, file = "../data/deg_group.csv",
#           row.names = FALSE)
# write.csv(tb_nadm, file = "../data/deg_nadm.csv",
#           row.names = FALSE)
# write.csv(tb_mace, file = "../data/deg_mace.csv",
#           row.names = FALSE)
# write.csv(tb_death, file = "../data/deg_death_all.csv",
#           row.names = FALSE)
```

## Volcano plots

```{r}
pA <- plot_volcano(tb_group, "PWH with vs without SNAEs")
pB <- plot_volcano(tb_nadm, "PWH with vs without neoplasias")
pC <- plot_volcano(tb_mace, "PWH with vs without CV events")
pD <- plot_volcano(tb_death, "PWH with vs without mortality")
```

All together in one figure:

```{r}
# svg("../data/fig2AtoD.svg", width = 7, height = 5)
ggarrange(pA, pB, pC, pD, labels = c("A", "B", "C", "D"))
# dev.off()
```
