---
title: "Multiomics integration"
format:
  html:
    df-print: paged
    embed-resources: true
---

## Load libraries

```{r}
#| message: false
library(DESeq2)
library(ggpubr)
library(mixOmics)
library(tidyverse)
```

## Load (proteomics) data

```{r}
pdata <- read_tsv("../data/PRETTY_NPX_138samp_326prot_QCed.tsv")
mdata <- pdata |>
  dplyr::select(sid:death_all) |>
  distinct() |>
  arrange(sid)
mdata_rnaseq <- read_tsv("../data/PRETTY_metadata.tsv") |> 
  dplyr::select(sid, rnaseq_id, group)
```

## Load (transcriptomics) data

```{r}
load("../data/deseq2.dds.RData")
```

```{r}
assays(dds)
```

```{r}
rna_mat <- assay(dds, "vst")
dim(rna_mat)
```

```{r}
# Remove near-constant genes
vars <- apply(rna_mat, 1, var)
# Keep e.g. top 5000 most variable
rna_mat <- rna_mat[order(vars, decreasing=TRUE)[1:5000], ]
# DIABLO expects centered/scaled blocks
rna_mat <- scale(t(rna_mat))
```

## Create input for mixomics

```{r}
# Y_group <- mdata$group
Y_group <- factor(mdata$group, labels = c("No", "Yes"))
names(Y_group) <- mdata$sid
Y_nadm <- as.factor(mdata$nadm)
names(Y_nadm) <- mdata$sid
Y_mace <- as.factor(mdata$mace)
names(Y_mace) <- mdata$sid
Y_death <- as.factor(mdata$death_all)
names(Y_death) <- mdata$sid


pdata_mat <- pdata |> dplyr::select(sid, Assay, NPX) |> pivot_wider(names_from = Assay, values_from = NPX) |> arrange(sid)
X <- as.matrix(pdata_mat[, -1])
rownames(X) <- pdata_mat$sid
```

## PCA

```{r}
# run pca method on data
pca.pretty <- pca(X, ncomp = 10, center = TRUE, scale = TRUE)
# barplot of the eigenvalues (explained variance per component)
plot(pca.pretty)
# plot the samples projected onto the PCA subspace
plotIndiv(pca.pretty, group = Y_nadm, ind.names = FALSE, 
          legend = TRUE, title = 'PCA by group',
          ellipse = TRUE)
plotIndiv(pca.pretty, group = Y_nadm, ind.names = FALSE, 
          legend = TRUE, title = 'PCA by neoplasia',
          ellipse = TRUE)
plotIndiv(pca.pretty, group = Y_nadm, ind.names = FALSE, 
          legend = TRUE, title = 'PCA by CV event',
          ellipse = TRUE)
plotIndiv(pca.pretty, group = Y_nadm, ind.names = FALSE, 
          legend = TRUE, title = 'PCA by mortality',
          ellipse = TRUE)
```

```{r}
plotVar(pca.pretty, comp = c(1, 2),
        var.names = TRUE,
        cex = 3,         # To change the font size
        # cutoff = 0.5,  # For further cutoff
        title = 'Inflammatory proteins, PCA comp 1 - 2')
```

```{r}
biplot(pca.pretty, group = Y_group,
       ind.names = FALSE,
       legend.title = 'Biplot by group')
```

## sPCA

```{r}
grid.keepX <- c(seq(5, 30, 5))

# Uncomment to run parameter tuning, it takes a while to finish
# tune.spca.result <- tune.spca(X, ncomp = 3, 
#                               folds = 5, 
#                               test.keepX = grid.keepX, nrepeat = 50,
#                               BPPARAM = BiocParallel::MulticoreParam(workers = 10)) 

# Consider adding up to 50 repeats for more stable results
# tune.spca.result$choice.keepX
# plot(tune.spca.result)
# By default center = TRUE, scale = TRUE
# keepX.select <- tune.spca.result$choice.keepX[1:2]
keepX.select <- c(comp1 = 15, comp2 = 15)

final.spca.multi <- spca(X, ncomp = 2, keepX = keepX.select)

# Proportion of explained variance:
final.spca.multi$prop_expl_var$X
```

```{r}
plotIndiv(final.spca.multi,
          comp = c(1, 2),
          ind.names = FALSE,
          group = Y_group,
          ellipse = TRUE,
          title = "sPCA by group")
```

```{r}
plotVar(final.spca.multi, comp = c(1, 2),
        var.names = TRUE,
        cex = 3,         # To change the font size
        # cutoff = 0.5,  # For further cutoff
        title = 'Inflammatory proteins, sPCA comp 1 - 2')
```

```{r}
biplot(final.spca.multi, group = Y_group,
       ind.names = FALSE,
       legend = FALSE)
```

```{r}
plotLoadings(final.spca.multi, comp = 1)
```

```{r}
plotLoadings(final.spca.multi, comp = 2)
```

## DIABLO

### Load data

```{r}
id_map <- mdata_rnaseq
# Check what overlaps
intersect(rownames(rna_mat), id_map$rnaseq_id)

# Subset to mapped samples only
common <- intersect(rownames(rna_mat), id_map$rnaseq_id)

rna_mat <- rna_mat[common, ]

map <- id_map %>% filter(rnaseq_id %in% common)

# Ensure same order
map <- map[match(rownames(rna_mat), map$rnaseq_id), ]

stopifnot(all(map$rnaseq_id == rownames(rna_mat)))

rownames(rna_mat) <- map$sid

# Keep samples with both omics data
full_samples <- intersect(rownames(X), rownames(rna_mat))

rna_mat <- rna_mat[full_samples, ]
```

```{r}
# Proteomics subsetting
protein_mat <- as.matrix(pdata_mat[, -1])
rownames(protein_mat) <- pdata_mat$sid
protein_mat <- protein_mat[full_samples, ]

# Store as list
X <- list(protein = scale(protein_mat),
          mRNA = rna_mat)
# Outcome
Y_group <- factor(mdata_rnaseq |> filter(sid %in% full_samples) |> pull(group),
                  labels = c("No", "Yes"))
names(Y_group) <- mdata_rnaseq |> filter(sid %in% full_samples) |> pull(sid)
```

```{r}
summary(Y_group)
```

### Design matrix

```{r}
design <- matrix(c(0, 0.1,
                   0.1, 0), ncol = 2)
```

```{r}
res1.pls.pretty <- pls(X$mRNA, X$protein, ncomp = 1)
cor(res1.pls.pretty$variates$X, res1.pls.pretty$variates$Y)
```

### Number of components

```{r}
# Uncomment to run parameter tuning, it takes a while to finish
# diablo.pretty <- block.plsda(X, Y_group, ncomp = 5, design = design)
# perf.diablo.pretty = perf(diablo.pretty,
#                           validation = 'Mfold',
#                           folds = 10,
#                           nrepeat = 10,
#                           BPPARAM = BiocParallel::MulticoreParam(workers = 5)
#                           )
#perf.diablo.tcga$error.rate
 # Lists the different types of error rates
# Plot of the error rates based on weighted vote
# plot(perf.diablo.pretty)
```

```{r}
# perf.diablo.pretty$choice.ncomp$WeightedVote
```

```{r}
# ncomp <- perf.diablo.pretty$choice.ncomp$WeightedVote["Overall.BER", "max.dist"]
ncomp <- 2
```

### Number of variables to select

```{r}
# Uncomment to run parameter tuning, it takes a while to finish
# test.keepX <- list(mRNA = c(5:9, seq(10, 25, 5)),
#                    protein = c(5:9, seq(10, 25, 5)))
# tune.diablo.tcga <- tune.block.splsda(X, Y_group, ncomp = 2,
#                                       test.keepX = test.keepX, design = design,
#                                       validation = 'Mfold', folds = 10, nrepeat = 100,
#                                       dist = "max.dist",
#                                       BPPARAM = BiocParallel::MulticoreParam(workers = 8))
```

```{r}
# list.keepX <- tune.diablo.tcga$choice.keepX
# list.keepX
list.keepX <- list(protein = c(25, 25),
                   mRNA = c(25, 25))
```

### Final model

```{r}
diablo.pretty <- block.splsda(X, Y_group, ncomp = ncomp,
                              keepX = list.keepX, design = design)
```

### Sample plots

```{r}
plotDiablo(diablo.pretty, ncomp = 1)
```

```{r}
# svg("../data/fig_mixo_A.svg", width = 7, height = 7)
plotIndiv(diablo.pretty, ind.names = FALSE, legend = TRUE, ellipse = TRUE,
          title = '',
          legend.title = "SNAEs")
# dev.off()
```

```{r}
plotIndiv(diablo.pretty, ind.names = FALSE, legend = TRUE, ellipse = TRUE,
          block = "average",
          title = 'PRETTY, DIABLO comp 1 - 2')
```

### Variable plots

```{r}
plotVar(diablo.pretty, var.names = FALSE, style = 'graphics', legend = TRUE,
        pch = c(16, 17), cex = c(2, 2),
        col = c('darkorchid', 'brown1'),
        title = 'PRETTY, DIABLO comp 1 - 2')
```

```{r}
# svg("../data/fig_mixo_B.svg", width = 8, height = 5)
plotLoadings(diablo.pretty, comp = 1, contrib = 'max', method = 'median',
             legend.title = "SNAEs", title = "Top 25 contributing variables")
# dev.off()
```

```{r}
selectVar(diablo.pretty, comp = 1)
```

```{r}
circosPlot(diablo.pretty, cutoff = 0.7, line = TRUE,
           color.blocks = c('darkorchid', 'brown1'),
           color.cor = c("chocolate3","grey20"), size.labels = 1.5)
```

```{r}
# svg("../data/fig_mixo_C.svg", width = 7, height = 7)
circosPlot(diablo.pretty, cutoff = 0.5, line = TRUE,
           color.blocks = c('darkorchid', 'brown1'),
           color.cor = c("chocolate3","grey20"), size.labels = 1.5, comp = 1,
           legend.title = "SNAEs")
# dev.off()
```

### Exploring the correlation between variables

```{r}
corr.pretty <- circosPlot(diablo.pretty, cutoff = 0.6, line = TRUE,
           color.blocks = c('darkorchid', 'brown1'),
           color.cor = c("chocolate3","grey20"), size.labels = 1.5, comp = 1)
```

```{r}
deg_group <- read_csv("../data/deg_sig_group.csv")
dep_group <- read_csv("../data/dep_group.csv") |>
  filter(Threshold == "Significant")
```

```{r}
library(ComplexHeatmap)
library(grid)

# your heatmap matrix
mat <- corr.pretty[1:25, 26:50]

# character vectors with names to highlight
bold_prots <- intersect(rownames(mat), dep_group$Assay)
bold_genes <- intersect(colnames(mat), deg_group$gene)

# row & column names
rn <- rownames(mat)
cn <- colnames(mat)

# svg("../data/fig_mixo_D1.svg", width = 7, height = 7)
Heatmap(
  mat,
  row_names_gp = gpar(
    fontface = ifelse(rn %in% bold_prots, "bold", "plain")
  ),
  column_names_gp = gpar(
    fontface = ifelse(cn %in% bold_genes, "bold", "plain")
  )
)
# dev.off()
```

```{r}
bold_all <- c(bold_genes, bold_prots)
rn <- rownames(corr.pretty)
cn <- colnames(corr.pretty)
# svg("../data/fig_mixo_D2.svg", width = 10, height = 10)
Heatmap(
  corr.pretty,
  row_names_gp = gpar(
    fontface = ifelse(rn %in% bold_all, "bold", "plain")
  ),
  column_names_gp = gpar(
    fontface = ifelse(cn %in% bold_all, "bold", "plain")
  )
)
# dev.off()
```
